### ISSUE TITLE
remain warning prop `addTag`

### ISSUE THREAD

**Issue by bitmapdata** [olahol/react-tagsinput#110]
<img width="923" alt="screen shot 2016-09-20 at 13 40 33" src="https://cloud.githubusercontent.com/assets/3241312/18657720/c988cc92-7f37-11e6-8a06-d9eed110630f.png">

**Comment by baldwmic** [comment]
I'm also seeing this unknown prop warning for `addTag` prop

**Comment by lele85** [comment]
Same here.

**Comment by mhlmhl** [comment]
I have the same problem.  It only occurs when I use the suggested AutosizeInput component via         "renderInput={this.autosizingRenderInput}".

**Comment by mhlmhl** [comment]
I fixed this by adding the following to the autosizingRenderInput function that is suggested in the react-tagsinput FAQ:

`delete other.addTag;`

**Comment by olahol** [comment]
I will add to the documentation that you have to filter out `addTag`, older version of React used to no give errors when unknown props where passed to elements.

**Comment by olahol** [comment]
Now in the FAW https://github.com/olahol/react-tagsinput#how-do-i-fix-warning-unknown-prop-addtag
