### ISSUE TITLE
How to add 'key' and 'label' to tags.

### ISSUE THREAD

**Issue by aniyanm** [olahol/react-tagsinput#116]
How can I add a 'key' and 'label' to tags so that I can get that 'key' and 'label' on change event. But only label should be displayed as tags.

**Comment by Prophet32j** [comment]
Very easy. You simply need to override the renderTag function. You can take the default function from the code/docs, and then you can add what you need to it from there, all while maintaining the styles and default look. This comes in really handy with hovers being applied if you want to show a popover for additional information about a tag.

**Comment by aniyanm** [comment]
okay.. will try it..
