### ISSUE TITLE
Multiple calls to addTag fail

### ISSUE THREAD

**Issue by neemzy** [olahol/react-tagsinput#12]
Hi,

I've attached a closure to `onTagAdd`, where I check if the inserted tag contains whitespace. If it does, I remove this tag, split its value on whitespaces and add back every element of the resulting array.

The expected is result is that when I paste "aaa bbb ccc", I get 3 separate tags, respectively "aaa", "bbb" and "ccc". Instead, only the **last** call to `addTag` succeeds, and the former tag (with spaces in it) remains, which in this example fives me "aaa bbb ccc" and "ccc".

Here is the code I use :

```javascript
React.createClass({
    splitTags: function(tag) {
        var tags = tag.split(/\s+/);

        if (1 < tags.length) {
            this.refs.tags.removeTag(tag);

            tags.forEach(function (splittedTag) {
                this.refs.tags.addTag(splittedTag);
            }.bind(this));
        }
    },

    render: function() {
        return (
            <ReactTagsInput
                ref="tags"
                onTagAdd={this.splitTags}
            />
        );
    }
});
```

I tried a simpler case, where the `splitTags` method's body only consists of the following :

```
this.refs.tags.removeTag(tag);
this.refs.tags.addTag('aaa');
this.refs.tags.addTag('bbb');
this.refs.tags.addTag('ccc');
```

The result, when validating "aaa bbb ccc", is "aaa bbb ccc" "ccc" "bbb".

Is `addTag` asynchronous ? Does it accept a callback, yield a Promise, anything that could help me manage this properly ?

Thanks a lot !

**Comment by olahol** [comment]
Thank you for bringing this bug to my attention. `addTags` is asynchronous when the component is uncontrolled, I had missed this case so the internal state was being mangled. I have fixed the bug by using the new transactional states in React 0.13. I have pushed a new version 1.3.3 with the fix.

Also have you tried adding space (keycode 32) to the `addKeys` prop? Or this not viable in your case?

**Comment by neemzy** [comment]
Thanks for the quick reply, and for the fix of course !

- I'm requiring your library through Bower and the 1.3.3 tag seems unavailable there as of now, could you look into it ? :)
- Actually, I *do* use 32 as an extra value for `addKeys`, I left it out of my example for the sake of simplicity. It did not trigger tag splitting on its own because the Space character was pasted in, and the key wasn't pressed. But what I am trying to achieve here is indeed a complement for this.

Thanks again !

**Comment by olahol** [comment]
Oops, I am so sorry I don't use Bower myself so I missed the pushing the new tag :pensive: It's up now.

Ok, I see what you are doing now.

Check if version 1.3.3 fixes the issues and get back to me.

**Comment by neemzy** [comment]
It works perfectly ! Thanks again :)

**Comment by olahol** [comment]
:+1:
