### ISSUE TITLE
Feature wanted, auto enter tags

### ISSUE THREAD

**Issue by ryanbelt** [olahol/react-tagsinput#121]
is there any ways to let the input box auto create tag If some condition satisfy?
```js
function defaultRenderInput (props) {
  let {onChange, value, addTag, ...other} = props

  if(value.length == 12){
    console.log(props,value)
    addTag(value);
  }
return (
      <input type='text' onChange={onChange} value={""}/>
    )

}
```
for example, i want to add a tag automatically when it has 12 chars long .

with this build i got some error 
```
Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.
``` 

any suggestion ?

**Comment by olahol** [comment]
You can do it by controlling the input of the component, there is an example [autoadd.js](https://github.com/olahol/react-tagsinput/blob/master/example/components/autoadd.js)

**Comment by AbhaysinghBhosale** [comment]
@ryanbelt have you got to fix it to auto add the tag. i want to auto add the tag if it is valid email address
