### ISSUE TITLE
Warning: Failed prop type: The prop `value` is marked as required in `TagsInput`, but its value is `undefined`.

### ISSUE THREAD

**Issue by 58a36f** [olahol/react-tagsinput#130]
Getting this error:

`Warning: Failed prop type: The prop `value` is marked as required in `TagsInput`, but its value is `undefined`.`

I do not have unique set to true.

Also it cause another errors:

`Uncaught TypeError: Cannot read property 'map' of undefined`

**Comment by olahol** [comment]
You need to pass an array into `value` prop, look at the example in the documentation:

```js
import TagsInput from 'react-tagsinput'

import 'react-tagsinput/react-tagsinput.css' // If using WebPack and style-loader.

class Example extends React.Component {
  constructor() {
    super()
    this.state = {tags: []}
  }

  handleChange(tags) {
    this.setState({tags})
  }

  render() {
    return <TagsInput value={this.state.tags} onChange={::this.handleChange} />
  }
}
```
