### ISSUE TITLE
Possible to add unique class name to only certain tags?

### ISSUE THREAD

**Issue by patryk0605** [olahol/react-tagsinput#132]
I am using tags as a filter and have a case where a user might want to negate a tag (example: show everything with tag **a**, but not tag **b**). To accommodate this, I added a checkbox via `renderInput` which would prepend a **!** when checked to the tags via `onChange` until unchecked again. That's all working fine, however I was wondering is it possible to add a specific class to these negated tag containers? I saw there is a `tagProps`, but that applies a class to all tags instead of specific.

**Comment by olahol** [comment]
I think what you want is `renderTag`.

**Comment by patryk0605** [comment]
@olahol Ha, I must be blind. Thanks!
