### ISSUE TITLE
Submit on adding no tag (question)

### ISSUE THREAD

**Issue by ryanhyslop** [olahol/react-tagsinput#134]
Fantastic configurable component, thank you!

Was wondering if anyone had a similar use case as to one thats appearing for me.

With default addKeys pressing return will add a new tag - great.  To actually submit the form however users need to tab out of the input and return or cursor to submit button.

Given that the tab reverts to its usual behaviour when the input is empty, perhaps theres a use case to make return not `e.preventDefault` if the tag input is empty? So I can add tag and submit again to search?

Seems like this behaviour is hard coded in unless I'm missing a trick, (https://github.com/olahol/react-tagsinput/blob/master/src/index.js#L287).

Appreciate this may not be for everyone so would need to be a prop `submitOnEmpty` or something? Any thoughts from others on this as could contribute a PR for this?

**Comment by olahol** [comment]
Fixed in version `3.16.0`.
