### ISSUE TITLE
Request feature: Editable tags feature

### ISSUE THREAD

**Issue by rumanhassan** [olahol/react-tagsinput#137]
HI 

Is it possible to edit the tags, i have used this library for tags in my project, now we have a requirement to add edit functionality, so that user can edit the tags. Currently this library doesn't seems to support edit functionality? Do we have any plans to add it in near term?

Any help or suggestion is really appreciated.

Thanks
Ruman.

**Comment by martin-svk** [comment]
I would really appreciate this...

**Comment by iliasbhal** [comment]
You can use the render "renderTag" prop and make the tag an editable tag.
