### ISSUE TITLE
Timing Problem With onTagRemove method

### ISSUE THREAD

**Issue by buzcarter** [olahol/react-tagsinput#15]
Thanks for building this, it's proved a tremendous help, but I am experiencing one oddity with respect to the timing of events when a tag is removed.

My `onTagAdd` and `onTagRemove` callbacks call the `getTags` method:

```javascript
_onTagAdd: function (tag) {
    console.log('add', this.refs.tags.getTags());
},
_onTagRemove: function (tag) {
    console.log('remove', this.refs.tags.getTags());
},
```

The list is correct for `onTagAdd` (the new tag has been included), however, for `onTagRemove` the list still contains the deleted tag. Thinking it was a timing issue I added a `componentDidUpdate` handler to my component:

```javascript
componentDidUpdate: function (argument) {
    console.log(this.refs.tags.getTags());
},
```

Now the list is correct for both add and remove actions. Looking in `react-tagsinput.js` I note that whereas the `addTag` call to the React `setState` method includes a callback, `removeTag` does not. This is where I think the problem lies. If the remove method is structured like the add, with a callback for `setState` invoking the `onTagRemove` prop, the problem seems fixed:

```javascript
    , removeTag: function (tag) {
      this._valueTransaction(function (value) {
        var clone = value.concat([]);

        for (var i = 0; i < clone.length; i += 1) {
          if (clone[i] === tag) {
            clone.splice(i, 1);

            this.setState({
              tag: ""
              , invalid: false
            }, function () {
              this.props.onTagRemove(tag);
            });

            return clone;
          }
        }
      }.bind(this), tag);
    }
````

Has anyone else experienced this problem or is this my user error? I made a branch with the proposed fix (easiest way to test is by adding the feedback on `completion.html` as I did above)

Thanks again for this component!

**Comment by olahol** [comment]
Thank you for bringing this to my attention, it's definitely a bug that onTagAdd and onTagRemove are being executed at different times (onTagAdd after a tag has been added, and onTagRemove before a tag has been added). I will have fix done in a minute.

**Comment by buzcarter** [comment]
Thanks... you're setting a speed standard I don't want to live up to. Much appreciated!

**Comment by olahol** [comment]
Doing it fast was easy when you provided the solution :wink: Thanks again.
