### ISSUE TITLE
Opt for key names rather than keyCodes

### ISSUE THREAD

**Issue by augbog** [olahol/react-tagsinput#155]
For specific properties in the `react-tagsinput`, we depend on passing keyCodes i.e. `addKeys` property.

According to MDN, [`keyCode` is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and it's better to opt for `e.key` as opposed to `e.keyCode`. I understand this would probably be a big breaking change but considering `keyCode` is deprecated, it might be worth making the switch? Or somehow supporting both `e.key` values and/or `e.keyCode` values.

**Comment by olahol** [comment]
This is fixed by #156 which is in version `3.18.0`. Thank you.
