### ISSUE TITLE
Features: Clear On 'Escape' Key, Propagate onKeyDown Event

### ISSUE THREAD

**Issue by buzcarter** [olahol/react-tagsinput#16]
I'm quite pleased with how easy working with this has been -- particularly the completion example y'all provided. I've [forked the code](https://github.com/buzcarter/react-tagsinput) to add two somewhat related features:

1. clear the input field when user hits `escape`;
2. propogate the KeyDown event;

I suspect the first one (to clear input) is more univerally useful, however, if one's using this as demonstrated in the completion example (ala Typeahead) the suggestions should be cleared when the input is cleared. Watching the *Key Down* allows me to do this.

I'm still tinkering, so code may not be that great, or there might be a cleaner way to do this (for example, fire a "onInputCleared" method), or it's already possible.

Handling escape is easy:

```javascript
    , onKeyDown: function (e) {
      var add = this.props.addKeys.indexOf(e.keyCode) !== -1
        , remove = this.props.removeKeys.indexOf(e.keyCode) !== -1;

      if (e.keyCode === 27){
        this.setState({
          tag: ""
          , invalid: false
        });
      }

      // ... more code here
    }
```

Likewise, if it's useful, passing along the KeyDown is, too
```javascript
    , onKeyDown: function (e) {
        // do exising stuff... then:

        if (!add && !remove){
          this.props.onKeyDown(e);
        }
    }
```

Then, back in my component:
```javascript
  _onKeyDown: function (keyEvent) {
    if (keyEvent.keyCode ===  27) {
        this.setState({ suggestions: []});
    }
  },
```

Thanks again for all of your work.

(Sorry for logging feature requests here, wasn't sure where else to send it. I'm not offened when you Close this out.)

**Comment by olahol** [comment]
These things look like great additions :+1: I will try to implement them today after work (~18:00 CET)

**Comment by buzcarter** [comment]
Again: thanks and fantastic!

Bit of background: part of my thinking for "bubbling" the *KeyDown* to the parent is not just to catch the `escape` key (to clear suggestions), but to also capture the *DownArrow*, this would shift focus and begin navigation through a suggestions list. One of the beauties of Bootstrap's Typeahead being its seamless means of moving from typing/hinting to selecting a suggestion without requiring switching from keyboard to mouse.

And, should I get really ambitions (hmmm), I'd thought *tabbing* in an empty input field might jump to next input on the parent form... no clue yet how I might do that :smile: . 

Thanks for looking at all this.

**Comment by olahol** [comment]
Alright, I have added an `onKeyDown` prop and a method `clear` in a9481fd8796978caa7df421ee24b91a726715deb that should make what you want to do possible.

**Comment by wdlb** [comment]
I just had a look at the documentation and the source code, and it looks like this feature is gone. Was it deliberately removed? Are there any other options to accomplish the same, e.g. doing special stuff on Escape and/or ArrowDown presses?
