### ISSUE TITLE
Add tag with space

### ISSUE THREAD

**Issue by frods** [olahol/react-tagsinput#161]
What is the recommended way to prevent space from adding a tag. So that tags can contain spaces. This way tags will be added only when enter is pressed.

**Comment by 0nn0** [comment]
@frods: The example already allows for spaces in tags: https://olahol.github.io/react-tagsinput/

If you use the `addKeys` prop, ensure it does not contain keycode `32` which represents the spacebar.

**Comment by olahol** [comment]
Thanks for answering the question @frods :)

**Comment by frods** [comment]
Thanks that did the trick.
