### ISSUE TITLE
Make Tab/Enter pick the first auto-suggested value

### ISSUE THREAD

**Issue by samerbuna** [olahol/react-tagsinput#162]
Hello,

Thanks for a great tags input option. Very easy to set up.

I am using it with Autosuggest and everything is working exactly as it should except one thing that I'd like to customize: When having a suggestion list open with a partially typed match, I'd like Tab and Enter to pick the first auto-suggested value instead of the partially typed value.

I could not find a way to do that. Is this possible at all?

**Comment by aaronbeall** [comment]
Related to this, with `react-autosuggest` it's supposed to set the value when you press Up/Down arrow keys to the highlighted value, but that doesn't seem to work in `react-tagsinput`.
