### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ashfaqrafi** [olahol/react-tagsinput#163]
I am looking for a feature like I can be able to copy and paste a bunch of words separated by comma and when I paste it on the input box all the separated words will be looking like tags as now in the package. Like I want to copy a bunch of words like this 
household, family, family circle, ménage, clan, tribe
and when I paste this in the input box it will look like separated tags. Is this done in the repo yet or if not is it possible to add some code in the existing package to achieve this feature? if I need to add some code to get this feature please suggest me.

**Comment by mykter** [comment]
Does this do what you need? https://github.com/olahol/react-tagsinput#pastesplit
