### ISSUE TITLE
Add styles to tags seperately

### ISSUE THREAD

**Issue by dinidu-bhathiya** [olahol/react-tagsinput#164]
I am looking for a feature where I can add styles to individual tags separately.  
I want to do things like make few of tags disable(add few tags at the bigging and make them not removable) and change the color of few tags (to show they failed validation). 

Are these features available in the react-tagsinput?

**Comment by Keshavdulal** [comment]
Currently in the exact same scenario.

**Comment by Keshavdulal** [comment]
@Diniduddd This ** closed issue** #154 helped me.
You should try checking that out.

**Comment by Diniduddd** [comment]
Hi @Keshavdulal 
I tried it. I could add different colors to tags with `renderTag `. Thank you very much.
