### ISSUE TITLE
How to set the width of the input

### ISSUE THREAD

**Issue by xero88** [olahol/react-tagsinput#165]
How to set the width of the input ?

Now it's very short

**Comment by kaueDM** [comment]
```
<TagsInput
   value={this.state.tags}
   onChange={this._handleTags}
   inputProps={{ placeholder: 'myPlaceholder', className:'myClass' }}
/>
```

Write your css using `myClass`. There you can set width.

**Comment by mykter** [comment]
would it make sense to remove the default 80px width of the input? It's typically going to be invisible to the user, so I'm not sure if there are any downsides to having it fill its container.
