### ISSUE TITLE
Set Focus To Input Field On Click Anywhere Within Control 

### ISSUE THREAD

**Issue by buzcarter** [olahol/react-tagsinput#17]
I made a simple [change on my fork](https://github.com/buzcarter/react-tagsinput/commit/f497677935220afdad6a84881e4328262482e54f) that you might want to include: make the tag control's wrapper div, the one with the `react-tagsinput` CSS class, "hot clickable": when user clicks anywhere within the containing div the tag's input field receives focus. A one line change since the required method already exists:

```Javascript
    , render: function() {
      // ... some code
      return (
        React.createElement("div", {
          className: ns + "tagsinput"
          , onClick: this.focus // <-- add this call
        }, // ... more stuff
```

Believe this makes the thing feel "more of a piece" -- a single, seamless control.

As always, thanks for this -- a demo with our users went exceptionally well yesterday, in no small measure thanks to this component. They didn't even end their comments with the usual "oh, but there is one more thing we need tweaked...". Bravo!

**Comment by olahol** [comment]
Yes this is a good change and has been request in another (pull request #14) :+1: Glad that your demo went well :smile: 

I'm just now implementing these things as I have had some unfortunate computer troubles :sob:

**Comment by olahol** [comment]
Added when clicking on component focusing the tag input in a9481fd8796978caa7df421ee24b91a726715deb . I added a wrapper to check if `click` event was actually fired from the `react-tagsinput`.

**Comment by buzcarter** [comment]
Thanks so much, Ola! Hope your computer issues (and these pesky requests) didn't keep you indoors all weekend, I really appreciate all the help.

**Comment by olahol** [comment]
Requests and issues are always welcome as they help make the component better, as for being indoors all weekend I'm outside right now enjoying the lovely summer weather in Gothenburg :smile:

**Comment by jacobrask** [comment]
This doesn't work for me in the demo. Try clicking to the right in the white box, nothing happens. Is it a regression?

**Comment by olahol** [comment]
I think I need to update the demo, it's horrible out of date. Can you test the file `example/index.html` while I update the demo?

**Comment by jacobrask** [comment]
Checked now, and it works in the example in the repository.

It didn't work for me in my application which is how I ended up here, but then I know that I should debug my own code :) thanks!

**Comment by olahol** [comment]
Glad to help :) Since the overhaul of the code in version 3 I'm always on the look out for regressions.
