### ISSUE TITLE
react jsx in render?

### ISSUE THREAD

**Issue by criso** [olahol/react-tagsinput#18]
Hi, I'm getting a warning:
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform.
when including this component because I'm using JSX. Any thoughts on how to get around this?

**Comment by olahol** [comment]
What version of React are you using?

**Comment by criso** [comment]
0.12.2

**Comment by olahol** [comment]
New versions of `react-tagsinput` require 0.13 or above.
