### ISSUE TITLE
Publish latest version

### ISSUE THREAD

**Issue by tknickman** [olahol/react-tagsinput#190]
If this repo is still being maintained, please publish the latest version of `react-tagsinput` to npm. Many users (including myself) would benefit from the latest features (most notability support for the `validate` prop as evidenced from https://github.com/olahol/react-tagsinput/issues/177). The fact that this repo has fallen out of date is causing many forks to be published as scoped modules, causing fragmentation and confusion.

If there are blocking issues preventing the publish (possible bugs, more test coverage etc.) , please post them here and I would be happy to help work on anything that we would need help get this released!

Thanks!

**Comment by ArtemBernatskyy** [comment]
CC @olahol

**Comment by driannaude** [comment]
@tknickman agree, but in the meantime, you can include the git repo address in your `package.json` to overcome this, It's not perfect and your code will most probably break if a breaking change is introduced in master though, but you could probably point it to a specific commit if needed?

```javascript
"react-tagsinput": "https://github.com/olahol/react-tagsinput.git",
```

**Comment by yairEO** [comment]
You can switch to Tagify: https://github.com/yairEO/tagify

**Comment by driannaude** [comment]
@yairEO thanks this looks like a great alternative!
