### ISSUE TITLE
in the latest version of react we get the following warning due to the use of deprecated APIs. Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

### ISSUE THREAD

**Issue by samals** [olahol/react-tagsinput#195]

**Comment by malizadeh22** [comment]
> @olahol is there any plans of changing it to react hooks or replacing the componentWillReceiveProps to componentDidUpdate ? As of now just to avoid the warning on react 16.9.0 temporarily componentWillReceiveProps could be changed to UNSAFE_(). I could create a PR for the same too, If you don't have any plan to do so

Hi
Use edited version of it.

[index.js.zip](https://github.com/olahol/react-tagsinput/files/3934939/index.js.zip)

**Comment by Hurtindonkey** [comment]
@samals @olahol will there be an update addressing this issue?

**Comment by mehmetdemiray** [comment]
I created new package for this problem.
https://www.npmjs.com/package/react-tagsinput-special

**Comment by andree-rehnberg** [comment]
@mehmetdemiray Thank you for this!
