### ISSUE TITLE
onpaste ?

### ISSUE THREAD

**Issue by Dror-Bar** [olahol/react-tagsinput#205]
Is the input's [onpaste](https://www.w3schools.com/jsref/event_onpaste.asp) property not exposed?
For example, I want to insert string directly after the user pastes it to Tagsinput.
Is this possible?

**Comment by brianweet** [comment]
Try https://github.com/olahol/react-tagsinput#addonpaste

**Comment by Dror-Bar** [comment]
@brianweet Thanks.
In my case, I wanted to add the string on paste, but also split it by comma (and not by space which is the default).
I accomplished it like this:

```
addOnPaste={true}
pasteSplit={str => str.split(',').map(d => d.trim())}

```
