### ISSUE TITLE
Restriction on number of tags

### ISSUE THREAD

**Issue by kockok** [olahol/react-tagsinput#21]
How to stop users from entering more tags if say, 10 tags already there?

I thought of disabling the Input component and adding a state of "maximum".

I know that I can customize your component to achieve this, but I would like an official implementation of this.

Thanks.

**Comment by olahol** [comment]
I think this would be possible by using the `beforeTagAdd` callback. Something like 

```javascript
handleBeforeTagAdd: function () {
  return this.refs.getTags().length <= 10;
}
```

**Comment by kockok** [comment]
Neat.
