### ISSUE TITLE
peer dependency conflict with react 18.x

### ISSUE THREAD

**Issue by nickpell** [olahol/react-tagsinput#211]
Unable to run npm install with react-tagsinput and React 18.x.
```
% npm --version
8.13.1
% npm install  
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: icebreaker-server@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^15.0.0 || ^0.14.0" from react-tagsinput@3.19.0
npm ERR! node_modules/react-tagsinput
npm ERR!   react-tagsinput@"^3.19.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by thatportugueseguy** [comment]
i bypassed this by installing with ``--force``. It's not ideal, but should work fine for the time being. This seems like a sort-of abandoned project, unfortunately. The last commit is from april 2018 🙈 

i think it should be quite easy to make a pr to fix this, but i'm not sure if it would get merged =/ 

@olahol ?

**Comment by ChristophP** [comment]
Hi there,
yeah I'm also having this issue with newer React versions.

Would be nice to get some sign of life from the maintainer if a PR would be accepted. @olahol

**Comment by ChristophP** [comment]
@olahol Thank you for taking care of this

**Comment by olahol** [comment]
Version `3.20.0` should work with React 18, 17, 15 and 14 now.
