### ISSUE TITLE
Passing objects as tags does not work because of trimming

### ISSUE THREAD

**Issue by andreymal** [olahol/react-tagsinput#220]
I made my tags not just strings, but objects that contain additional information (description, posts count etc.)

It worked fine for the last five years, but [this commit](https://github.com/olahol/react-tagsinput/commit/d5f27735b0e053f5c4f166eae116a024c4c28f2f) broke it because `arr[i].trim()` assumes that `arr` is an array of strings, but in my case it is an array of objects.

Since you [already considered a similar issue as a regression](https://github.com/olahol/react-tagsinput/pull/105), I think this is another regression which would be nice to fix.

(By the way, I'm not sure tags really need to be trimmed. There could be a theoretical use case where trimmed and non-trimmed tags should be treated as different tags)

**Comment by olahol** [comment]
Should be fixed in version `3.20.2`.

**Comment by andreymal** [comment]
@olahol hmm the npm package doesn't contain this fix for some reason

**Comment by olahol** [comment]
Looks like `prepublish` was deprecated and the compiled source was not pushed to NPM. Fixed in `3.20.3`.
