### ISSUE TITLE
Callback for invalid tag

### ISSUE THREAD

**Issue by yulric** [olahol/react-tagsinput#23]
Hi there,
I have a use case where I want to show an error message when the user attempts to add an invalid tag. I don't see any way of doing it right now with the current API unless I use the onChange prop. How I see it working is to to have a prop field called onInvalidTag which gets called in the this.validation method when the validation fails. Any thoughts or is there already a way of doing this?

Thanks a lot.

**Comment by olahol** [comment]
It's possible to do this by writing your own `validate` function, here is an example: 

```javascript 
validate: function (tag) {                                                      
  var tags = this.refs.tags.getTags();                                          
                                                                                
  if  (tags.indexOf(tag) > -1) {                                                
    this.onInvalidTag(tag);                                                       
    return false;                                                               
  }                                                                             
                                                                                
  return true;                                                                  
},              
```
