### ISSUE TITLE
Better way to clear/reset tagsinput

### ISSUE THREAD

**Issue by troyconquer** [olahol/react-tagsinput#25]
Hi there,

Currently doing my first bigger project in react. Thank you for the library btw, very handy.

I'm processing a list of tags with a button, all fine. Once I've "processed" the tags and show them in another read-only view. That is all working fine.

But I want to reset or clear the input box of any tags. I have something that works, but I'm getting some code smell and figured there is a better way to accomplish the task. If not, no worries. Just thought I'd ask.

Anyways.. the codes.
```
var TagComponent = React.createClass({
  ...
   processTags: function(){
      GlobalActions.processTags(this.refs.tags.getTags());
 
     //code in question
      _each(this.refs.tags.getTags(), function(tag){
        this.refs.tags.removeTag(tag);
      }.bind(this));
    },
   ...
   render: function() {
    return (  
      <div>
           <TagsInput ref='tags' placeholder='Add tag'/> 
           <button type='button'  onClick={this.processTags}>Process tags</button>
      </div>
    );
  }
  });

**Comment by olahol** [comment]
Currently when using the component in uncontrolled mode, this is probably the best way of deleting all the tags. The `clear` method is for clearing the text input.

**Comment by troyconquer** [comment]
Gotcha. thanks
