### ISSUE TITLE
Can't enter new tags in input complete mode

### ISSUE THREAD

**Issue by Death4ngel** [olahol/react-tagsinput#28]
In the input complete mode as shown in https://github.com/olahol/react-tagsinput/blob/master/example/completion.html, pressing the enter key does nothing and hence, no new tags can be created.

**Comment by olahol** [comment]
I'm not sure I understand the issue, when I press enter when there is just one match it adds the President.

**Comment by Death4ngel** [comment]
Yes, if there is just one match, it'll add that tag. However, what if I want to create an entirely new tag that is not in the President List? Pressing enter in this case does nothing at all.

**Comment by olahol** [comment]
Yes, that's the intended behavior in this case, to have a list of only correct tags.
