### ISSUE TITLE
Css float: left issues with tags

### ISSUE THREAD

**Issue by radubrehar** [olahol/react-tagsinput#33]
I had some issues when removing tags and as a result the input field was displayed before some of the tags. In my configuration, I removed `float: left` and added `display: inline-block` for tags, and it worked like a charm.

**Comment by olahol** [comment]
Sorry for not getting back to you sooner, thank you for the suggestion, I have updated the example stylesheet :+1:.

**Comment by radubrehar** [comment]
No problem, no need to apologise. I'm an OSS maintainer myself and know how it's like to have a multitude of issues from different projects :)

Another suggestion would be to add a `renderInput` prop (of type function) to allow the user to customize the input. I needed this, but ended up restyling the input with css and the main tag container as well.

**Comment by radubrehar** [comment]
See https://github.com/zippyui/react-date-picker#props for example. We offer `renderDay` and `onRenderDay` to allow full control over what it's rendered

**Comment by olahol** [comment]
Thanks for the suggestion :) The date picker looks great. Adding a `renderInput` and is a really good idea I will look into it this week.
