### ISSUE TITLE
Using with react 0.14

### ISSUE THREAD

**Issue by mjw56** [olahol/react-tagsinput#34]
Hi,

I tried installing this with react 0.14-beta3 but it will not install using npm 2.x because of peerDependency.

I'm not sure if you've tested this against 0.14 yet, and if you plan to support 0.14?

Thank you.

**Comment by olahol** [comment]
Yes I plan on supporting react 0.14, haven't tested it yet, but I will see if I can make it work, thanks for bringing it up :+1:

**Comment by mjw56** [comment]
thanks @olahol :)

**Comment by olahol** [comment]
There is now version a `1.5.0-beta1` on npm that should work with React `0.14.0-beta`.
