### ISSUE TITLE
Browser Compatibility?

### ISSUE THREAD

**Issue by cyberglot** [olahol/react-tagsinput#35]
(I know it's very annoying and everything, but...) Do you know the current browser compatibility of react-tagsinput? I am working in a project that I **must** support IE8+, unfortunately.

Thanks anyway.

**Comment by olahol** [comment]
No problem :smile:, the component should work on IE8 if you are using the normal polyfills/shims (es5-shim and es5-sham), I just tested the basic functionality in an IE8 virtual machine and everything looked ok.
