### ISSUE TITLE
add `onFocus`

### ISSUE THREAD

**Issue by ksmth** [olahol/react-tagsinput#37]
Pretty self explanatory - there's currently no good way to add a proper focus ring around the complete input.

**Comment by olahol** [comment]
Thank you, `onFocus` should definitely be there, fix is in version `1.4.5`.

**Comment by ksmth** [comment]
nice :+1:

**Comment by wembernard** [comment]
it seems that the `onFocus` feature has been lost in the 3.x releases?

**Comment by wembernard** [comment]
Ok, after digging into the code, you can do it like this:

```
render() {
  const inputProps = {
    onFocus: function() { console.log('onFocus') }
  }
  
  return (
    <TagsInput inputProps={inputProps} />
  )
}
```

Hope this helps 👍
