### ISSUE TITLE
don't prevent tabbing when there's no input value

### ISSUE THREAD

**Issue by ksmth** [olahol/react-tagsinput#38]
When tabbing through the interface, you get stuck in the input field, even if there's no value. It'd be nice if you could leave the input by hitting the `tab` key in this case.

**Comment by ksmth** [comment]
that was quick :dancer:

**Comment by olahol** [comment]
Good catch :+1:

**Comment by olahol** [comment]
Just doing some light coding with my morning coffee :smile:

**Comment by remyferre** [comment]
It seems this feature was removed in version 3. Is it a bug ?

Starting from [this commit](https://github.com/olahol/react-tagsinput/blob/01df702f20c4f751ee2f5cd528098249b819698d/react-tagsinput.js#L116), `handleKeyDown` no longer checks whether the input is empty or not.

**Comment by olahol** [comment]
You are right, this is a regression from version 1.

**Comment by olahol** [comment]
This is now fixed in version `3.6.1`, thank you @remyferre

**Comment by remyferre** [comment]
Great :smile:  Thanks for the quick response !

**Comment by Zhouzi** [comment]
@olahol the bug seems to be back, the tab behavior is prevented even when the input is empty. It's reproducible in the demo: https://olahol.github.io/react-tagsinput/
