### ISSUE TITLE
1.5.0 should be 2.0.0 (react 0.14)

### ISSUE THREAD

**Issue by iest** [olahol/react-tagsinput#43]
[Updating to depend on react 0.14 and react-dom 0.14](https://github.com/olahol/react-tagsinput/commit/51086f08ed923b76de594f94c286f1af2af6662e) is a breaking change, and the version number should reflect that (2.0.0).

If you have `"react-tagsinput": "^1.3.3"` in your package.json (like I do), you have to hard-set the version to whatever pre-1.5 release was now, which — although is not the end of the world — is both annoying and against npm's idea of semver.

**Comment by olahol** [comment]
Sorry, you are completley right, I got a little bit ahead of myself, what should I do to fix this? `npm unpublish` or `npm deprecate`?

**Comment by iest** [comment]
No problem! Thanks for being so responsive :blush: 

At first guess, `npm unpublish` — so people don't accidentally install it. [From the docs](https://docs.npmjs.com/cli/deprecate) it feels like `deprecate` is more for when a package works but is old or unmaintained or something...

**Comment by olahol** [comment]
Alright it's done, `1.5.0` is unpublished and `2.0.0` for React 0.14 is up, thank you for your help @iest :smile:

**Comment by iest** [comment]
:raised_hands:
