### ISSUE TITLE
I think u can remove require of react-dom

### ISSUE THREAD

**Issue by pmjhonwang** [olahol/react-tagsinput#44]
use   React.findDOMNode function

**Comment by olahol** [comment]
I get the warning `React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.` when I do this.

**Comment by pmjhonwang** [comment]
my react version was  React v0.13.3
![there was React.findDOMNode function](https://cloud.githubusercontent.com/assets/1998455/10515466/3447e824-7386-11e5-9d2f-4dca262949e9.png)

**Comment by olahol** [comment]
I see, version `2.0.0` of `react-tagsinput` uses React `0.14`. If you want to use React `0.13` use version `1.4.7` of `react-tagsinput`.

**Comment by pmjhonwang** [comment]
Thx a lot.
