### ISSUE TITLE
Configuring the layout of input & tags

### ISSUE THREAD

**Issue by michaeljones** [olahol/react-tagsinput#47]
Hi,

I'm considering a layout where I have an input field and the tags below it. This would allow me to give the user more room to type stuff before creating tags. This is because my interest is in being able to paste in a bunch of emails and create a set of tags from the emails so the current input field is a little small.

I thought we might be able abstract the piece of code at the end of the render function that outputs the div, tags & input to either be a function or another component which can then be overridden by a prop for people who would like to customise it? A function would take the tags and input node as arguments and return the final JSX. I suspect a function might be simpler so that output is still owned by the main component rather than a child.

I would also be curious to allow use of a textarea instead of an input field if you would consider that.

I'm not sure if these are deviating too far from your vision for the project though. I realise that at a certain point it might as well just be another component :)

Thanks for making this project available,
Michael

Edit: I'm very happy to make a pull request if this is something you'd consider.

**Comment by lightninglu10** [comment]
Is there a resoluion to this?
