### ISSUE TITLE
Functionality lost in v3?

### ISSUE THREAD

**Issue by eddiemoore** [olahol/react-tagsinput#51]
What happened to all the other functionality that tags input had in v2? v3 seems like a step back.

**Comment by olahol** [comment]
What functionality are you missing? I think the component is more flexible now with custom rendering and custom props, although that does make it a little bit more cumbersome to do some stuff.

**Comment by eddiemoore** [comment]
```.clearInput()``` ```onTagAdd``` ```onTagRemove``` ```onChangeInput``` How can I do all of these now?

**Comment by olahol** [comment]
All those things are possible just in a different way since the component is fully [controlled](https://facebook.github.io/react/docs/forms.html#controlled-components) now, just like standard react elements like `input` and `textarea`. Here is one way you could do it those functions:

```js
class Example extends React.Component {
  constructor() {
    super()
    this.state = {tags: []}
  }

  clearInput() {
    this.setState({tags: []});
  }

  onTagAdd(tag) {
    console.log(tag);
  }

  onChangeInput(input) {
    console.log(tag);
  }

  handleChange(tags) {
    if (tags.length > this.state.tags.length) {
      this.onTagAdd(tags[tags.length - 1]);
    }

    this.setState({tags})
  }

  render() {
    return <TagsInput inputProps={{onChange: ::this.onChangeInput}} value={this.state.tags} onChange={::this.change} />
  }
}
```

**Comment by eddiemoore** [comment]
Ahh cool thanks for that

**Comment by eddiemoore** [comment]
Still clearing the input doesn't work though.

**Comment by eddiemoore** [comment]
I'm using the input as a search input to find users in a list. Then when the user clicks on the user it will add to the tags list. But the input doesn't clear when it gets updated.
