### ISSUE TITLE
Give close button a unique className

### ISSUE THREAD

**Issue by idolize** [olahol/react-tagsinput#52]
Since upgrading to `3.x` the close button no longer has a unique `className`.

The suggestion to make a CSS rule targeting `.react-tagsinput-tag a::before ` is not suitable for me because I am actually using `<a>` inside my tags themseleves, and thus there is no easy way to differentiate (via CSS) between the link in my tag name and the link for the "close" button.

**Comment by olahol** [comment]
I've added `classNameRemove` to `tagProps`.
