### ISSUE TITLE
Naming `ReactTagsInput ` module instead of leaving it anonymous makes RequireJS unable to load it

### ISSUE THREAD

**Issue by SalimBensiali** [olahol/react-tagsinput#53]
See line https://github.com/olahol/react-tagsinput/blob/master/react-tagsinput.js#L3.

**Comment by olahol** [comment]
I'm trying to figure out how to fix this as the name is add automatically by babel.

**Comment by SalimBensiali** [comment]
Ah Ok. I think I fixed it. Preparing a PR now.

Cheers,
Salim

**Comment by SalimBensiali** [comment]
Please see https://github.com/olahol/react-tagsinput/pull/54 and let me know what you think.

Cheers
