### ISSUE TITLE
Feature: Bootstrap integration

### ISSUE THREAD

**Issue by dbkaplun** [olahol/react-tagsinput#55]
Would be nice if there was a Component or even simply an example that uses the `label` class for tags and `form-control` for the `<input>`. This works great with the prepackaged style but making it work with Bootstrap is a bit different.

**Comment by olahol** [comment]
Sorry for not getting back to you sooner @dbkaplun, I will look into bootstrap integration.

**Comment by barrystaes** [comment]
I'd also like to use it with bootstrap, but i'd also have to note that its good to have something what is not dependent on a big front-end framework.

**Comment by rkovacevic** [comment]
+1

**Comment by oscar-g** [comment]
You could pass in `renderTag`, `renderInput` and `renderLayout` props to get the correct html.  For the input classes, you can use `inputProps` with className (see the docs).

It seems like this would be enough to render the bootstrap component with the correct markup and classes.

Personally, I agree with @barrystaes about not being dependent on another framework.

@barrystaes - I want to hear your input about autocomplete on #69.

**Comment by kolis** [comment]
I was also looking for bootstrap support, but as mentioned, the component is extremely flexible, and can be made bootstrap-compatible with the custom properties. A well designed component imo!
