### ISSUE TITLE
Required attribute

### ISSUE THREAD

**Issue by gil--** [olahol/react-tagsinput#56]
It looks like there was once a prop for required https://github.com/olahol/react-tagsinput/blame/f9063330ee0ec6db509d2b73f1e6dde613e9956e/README.md#L130 But I don't seem to see this in the code (https://github.com/olahol/react-tagsinput/commit/f9063330ee0ec6db509d2b73f1e6dde613e9956e) or the docs anymore.

How would we make it be required to enter at least 1 tag?

**Comment by olahol** [comment]
Hello @gil--, sorry it took so long for me to get back to you, I think the behavior you want can be done modifying the `inputProps` property. something like:

```
inputProps={{
required: this.state.tags < 1
}}
```
