### ISSUE TITLE
Easy way to "disable" it?

### ISSUE THREAD

**Issue by alvaro1728** [olahol/react-tagsinput#66]
Hi, I really like your great control and now I'm having to show it "disabled" in a certain cases.  Is there an easy way to do this?  Basically I would want to disable the input box and the "x" on the existing items to prevent deletions.

Thanks,
Alvaro

**Comment by alvaro1728** [comment]
I did a little more digging through the docs and found that I can pass values for inputProps and tagProps to let me disable it the way I want.  It's not exactly "easy", but it's doable and that's what's important.  I'll wrap your control inside my own to give it an easy interface.

Thanks,
Alvaro

**Comment by linchen2chris** [comment]
what is the values you pass to inputProps and tagProps to disable it ?

**Comment by olahol** [comment]
@linchen2chris I have added a boolean `disabled` prop in version `3.10.0` that you can use.
