### ISSUE TITLE
Is there a way to set a placeholder? For example "Add tags"

### ISSUE THREAD

**Issue by jforaker** [olahol/react-tagsinput#67]
Is there a way to set a placeholder?  For example "Add tags"

Seems there is one in your demo gif but not in the actual demo. 

My tags are populated dynamically, and sometimes it is an empty array. 

Thanks

**Comment by olahol** [comment]
Yes `inputProps`

```javascript

<TagsInput inputProps={{placeholder: "Whatever"}} />
````
