### ISSUE TITLE
Feature request: Restore default tab behavior when there are no tags to be completed

### ISSUE THREAD

**Issue by glortho** [olahol/react-tagsinput#74]
As it stands, you can't tab out of a tag field to the next field in a form. It'd be nice, at least as an option, to have tab act normally if the user hasn't typed anything to complete as a tag. This would let you hit tab once to finish your current tag, and then tab again to get out of the field.

**Comment by olahol** [comment]
Is this the same issue https://github.com/olahol/react-tagsinput/issues/38 ?

**Comment by glortho** [comment]
it is, sorry. closing.

**Comment by olahol** [comment]
no problem, I only fixed it in version 3 about a week ago :wink:
