### ISSUE TITLE
click on button - create new tag

### ISSUE THREAD

**Issue by MathiasLund** [olahol/react-tagsinput#76]
Is it possible to make a button the same functionality as enter click?

I would really like if people were able to write their tag, click a button next to the ReactTagsInput container and then the tag was created - instead of having to click enter.

Thanks in advance!

**Comment by olahol** [comment]
There is now, I've added a method `accept` on the component, now you can do something like:

```js
<div>
  <Tagsinput ref="tags" ... />
  <button onClick={() => this.refs.tags.accept()}>Add</button>
</div>
```

**Comment by MathiasLund** [comment]
Awesome, works great!
However, can you please prevent it from reloading the page on click of the button?

**Comment by olahol** [comment]
You will have to figure that out for yourself.

**Comment by MathiasLund** [comment]
Fixed it - thx for your assistance!
