### ISSUE TITLE
Specifying inputProps overwrites the default object and removes className

### ISSUE THREAD

**Issue by Zhouzi** [olahol/react-tagsinput#80]
For example, adding a placeholder will result in removing the className:

```javascript
<TagsInput onChange={::this.onChange}
                   value={this.state.tags}
                   inputProps={{ placeholder: 'add a tag' }} />
```

This is due to the fact that inputProps as a default value of `{ className: 'react-tagsinput-input' }` and gets replaced by the provided one (`{ placeholder: 'add a tag' }` in the example above).

The workaround is to just re-add the className to inputProps so it may not be a top priority though. I'll eventually submit a PR if it's something that deserves a fix.

**Comment by olahol** [comment]
Yes, maybe some merging of `inputProps` with the default value? I will look into it after work today.

**Comment by Zhouzi** [comment]
Yep, I guess the fix could be to change https://github.com/olahol/react-tagsinput/blob/master/src/index.js#L244 to:

```javascript
inputProps () {
  // eslint-disable-next-line
  let {onChange, ...otherInputProps} = this.props.inputProps
  return {
    ...defaultInputProps,
    ...otherInputProps
  }
}
```

And updating the defaultProps accordingly ^^

**Comment by olahol** [comment]
Thank you @Zhouzi , this now added in version  `3.8.1`.
