### ISSUE TITLE
onlyUnique = true results in reload when used inside a form

### ISSUE THREAD

**Issue by pravin-d** [olahol/react-tagsinput#86]
I have form inside which I'm using taginputs. When I set onlyUnique to true and try to enter a duplicate value, the whole page reloads. I guess a e.preventDefault() should be called for every "enter", or call the onChange() of the parent with the error. So that the parent decide either to prevent default form behaviour or not.Let me know how to fix this

The parent component is within react-router component. Please let me know if you need a jsfiddle or something.. thanks

**Comment by olahol** [comment]
I have to take some time to think about the exact behavior the component should have, will get back to you soon.

**Comment by pravin-d** [comment]
Sure..
Currently I'm using with the following hack
```
key: 'handleKeyDown',
      value: function handleKeyDown(e) {
      ..... 
       ++  if (add) {
       ++   this.accept()
       ++   e.preventDefault();
       ++ }
       --  if (add && this.accept()) {
       --   e.preventDefault();
       --  }
      .....
     }
```
Do let me know what you decide the behaviour should be

**Comment by olahol** [comment]
That was the behavior before this change https://github.com/olahol/react-tagsinput/pull/82 , but maybe a special case should be made for enter as it submits forms ...

**Comment by pravin-d** [comment]
Ok.. kinda confused on the expected behaviour for tab tho..let me check it out..
