### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by pravin-d** [olahol/react-tagsinput#87]
Hey guys.. great job.. making it all so configurable.. really top notch.. 
Currently I'm implementing a feature where a user can add a bunch of cities for a given country. Somehow using tags made sense here. However I want the user to be able to edit the values, change the order and be able to serialize and deserialize data to/from server. Would really appreciate  if these are present.. Do you have any plans to implementing the above ?

**Comment by olahol** [comment]
Not in version 3, but I will keep it in mind when I design version 4.
