### ISSUE TITLE
Allow a complex data structure for value

### ISSUE THREAD

**Issue by tanshul22** [olahol/react-tagsinput#89]
This is a really great plugin but it seems to be missing the support for a complex data structure backing up a tag. Often a tag is associated with some kind of an `ID` and possibly some more meta data. Any plans on changing the `tags` array like below?

```
var tags = [{
  id: 1,
  name: 'foo'
},{
  id: 2,
  name: 'bar'
}]
```

**Comment by olahol** [comment]
This is now possible with `tagDisplayProp` in version `3.12.0`. Just set it to `"name"` and you should get object in the format `{name: "tag"}` from `onChange`.

**Comment by tanshul22** [comment]
Thank you @olahol. Looks and works great!
