### ISSUE TITLE
Allow non-strings (specifically, React Components) to be rendered within tag.

### ISSUE THREAD

**Issue by scoarescoare** [olahol/react-tagsinput#9]
This library is great, thanks for all the work! I needed to extend it a bit so that I could drag/drop my tags once they were created.

I came across the `transform` function and noticed that its [contents are expected to be a string.](https://github.com/olahol/react-tagsinput/blob/8a647e49c67014dbb62d3de52c7a68ccfce5f2bf/react-tagsinput.js#L111)

I modified the library a little bit so that I could return more than just strings, like so:

```javascript
transform(tag) {
    return (
      <DraggableField tagText={tag}/>
    );
  },
```

Which allowed me to render this:

![hover tags](http://i.imgur.com/iStNXLH.gif)

Internally, I'm thinking of storing objects instead of strings and use `tag` as the key and the value could be whatever: strings, react components, etc. So instead of

    valueLink.value.concat([tag]);

I am thinking something like

    _.extend(valueLink.value, {tag, newTag} //newTag is the result of `format`

If you think this might be an appropriate feature addition, I can spend a bit more time on it, add a test, and make a pr. Thanks.

**Comment by olahol** [comment]
Thank you Scott for you contribution. This sounds like a great feature addition, it would be really nice to have components or elements represented as tags. 

I think that I might be possible to implement without having to change the data structure from a list to an object. I have created a first draft for a fix to this issue in branch [allow-non-strings](https://github.com/olahol/react-tagsinput/tree/allow-non-strings) with an example [completion.html](https://github.com/olahol/react-tagsinput/blob/allow-non-strings/example/component.html). Feel free to contribute and change the code if it doesn't fit your needs :smile:

**Comment by scoarescoare** [comment]
Great, glad you agree :smiley: 

I went through the branch and added a couple line notes. I noticed you override the `validate` hook, were you thinking the default `validate` would need to be overridden when returning anything but a string?

**Comment by scoarescoare** [comment]
P.S. Thanks for making that branch and putting the example together so quickly!

**Comment by olahol** [comment]
Great notes, I am definitely going to move the space to the CSS.

I was thinking that the default `validate` function would only be defined for strings and if you wanted to
handle other types you would need to write your own. That's why I added the `typeof == string` check there. I'm now thinking that this should be warning and not just a check (i.e console.warn("default validate is only defined for strings").)

Your idea about using an object with `key` and `value` would be doable, but I am worried that it might break backwards compatibility.

Do you think the solution in the branch would work for your use case?

**Comment by scoarescoare** [comment]
Yeah, the solution in the branch works for me. Before using your solution, I was relying on an object with a key so that I could reference all my tags easily by a string key. But I was able to get around that by assigning a `key` prop to my components and referring to them that way.


```javascript
transform(tag) {
    return (
      <DraggableField key={tag} tagText={tag}/>
    );
  },
```

And then I was able to filter/find/etc:

```javascript
this.state.tags.filter(tagItem => tagItem.key === 'some tag'
```

**Comment by olahol** [comment]
Alright, I have merged that branch to master and updated the library. I also added you as a contributor :+1:.

**Comment by scoarescoare** [comment]
Great, thanks for your help and for taking care of it so quickly!
