### ISSUE TITLE
Show/Edit modes for tags (show/hide X)

### ISSUE THREAD

**Issue by maullerz** [olahol/react-tagsinput#96]
In my forms, i have 2 modes - show & edit - for each control.

Show mode on blur.
<img width="400" alt="2016-07-29 18 56 40" src="https://cloud.githubusercontent.com/assets/5295025/17254640/493ce7aa-55be-11e6-95bd-b5d7899eb58a.png">

Edit mode on focus.
<img width="488" alt="2016-07-29 18 56 51" src="https://cloud.githubusercontent.com/assets/5295025/17254645/4a4799f6-55be-11e6-96c8-bda15418f814.png">

visibility of X is managed by focused class of react-tagsinput.
Issue is when i try to remove tag the input-onBlur triggered and state become unfocused and X become hidden so click on X not triggered.

**Comment by stefanbuck** [comment]
We had a similar problem with our component which works basicly the same. We managed that by using a flag which is set to `false` on `MouseLeave` and to `true` on `MouseOver`. I hope this helps you.

```js
  onBlur() {
    if (this.state.hovered) {
      this.toggleFocus(true);
      return;
    }

    this.state.onBlur.apply(null, arguments);
  }
```

**Comment by maullerz** [comment]
I tried several own workarounds, but failed.
@stefanbuck can you explain your workaround with a bit more details?
How managed `this.state.hovered`?
What `toggleFocus` doing?
What is `this.state.onBlur`?

**Comment by maullerz** [comment]
@stefanbuck thanks for bump my mind!
Just did workaround using only css

```
  className={styles.tagsinput}
  focusedClassName={styles.focused}

  tagProps={{
    className: styles.tag,
    classNameRemove: styles.remove
  }}
```


```
.tagsinput {
  ...

  &.focused {
    border-color: #37C1CF;
    .remove {
      display: initial;
    }
  }

  &:hover {
    .remove {
      display: initial;
    }
  }
}

.remove {
  display: none;
  ...
}
```

but this annoying blinking of tags on mouse over....

**Comment by stefanbuck** [comment]
A slightly more complete example. What we basically are doing is creating a wrapper which handles the `onBlur` callback based on the local state prop `hovered`.

```js
onBlur() {
  if (this.state.hovered) {
    this.toggleFocus(true);
    return;
  }

  this.state.onBlur.apply(null, arguments);
}

toggleHoveredState(hovered) {
  this.setState({ hovered });
}

toggleFocus(focused) {
  if (focused) {
    this.refs.tagsinput.focus();
    return;
  }

  this.refs.tagsinput.blur();
}

render() {
  return (
    <div
      onClick={ this.toggleFocus.bind(this, true) }
      onFocus={ this.toggleFocus.bind(this, true) }
      onMouseLeave={ this.toggleHoveredState.bind(this, false) }
      onMouseOver={ this.toggleHoveredState.bind(this, true) }>
      
      <ReactTagsInput
          ref="tagsinput"
          inputProps={ {
            onBlur: this.onBlur.bind(this),
          } } />
    </div>
  );
}
```
