### ISSUE TITLE
Ability to run custom validation func

### ISSUE THREAD

**Issue by th3fallen** [olahol/react-tagsinput#98]
Is it possible to run a custom function to validate a tag being added? what i need to validate is a bit to complex to be done via a single regex?

i pray the answer is not no...

**Comment by olahol** [comment]
It's possible to just modify the `onChange` function and not add the tag if it's not valid.

**Comment by th3fallen** [comment]
That's what im doing at the moment but the issue im running into is in my onchange handler im validating and if it fails the validation it just nukes the current value so the input goes blank what i want is to keep the invalid value and show an error... heres' what im doing atm. Granted im going to move from doing tags.map to doing just the tag that's being added via the second param.

```
handleChange(tags) {
    let filteredTags = [];
    let data = { tags: filteredTags };
    tags.map((v) => {
      if (validator.isEmail(v) || validator.isMobilePhone(v, 'en-US')) {
        filteredTags.push(v);
        data.currentValue = '';
      }
    });
    this.setState(data);
  }
```
