### ISSUE TITLE
DOM nodes have invalid DOM props attached

### ISSUE THREAD

**Issue by andreieftimie** [olahol/react-tagsinput#99]
Just updated both react and react-tagsinput and I have the following warnings in the console:

```
Warning: Unknown prop `addTag` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

Warning: Unknown props `getTagDisplayValue`, `classNameRemove` on <span> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```

Full link describing the issue https://facebook.github.io/react/warnings/unknown-prop.html

**Comment by angelo-romano** [comment]
Same issue here. Only the first one though. Anyone?

**Comment by angelo-romano** [comment]
I assume it is being caused by this piece of code, where `addTag` is attempted to be injected as part of an `input` object.
```
var inputComponent = renderInput(_extends({
          ref: 'input',
          value: tag,
          onPaste: this.handlePaste.bind(this),
          onKeyDown: this.handleKeyDown.bind(this),
          onChange: this.handleChange.bind(this),
          onFocus: this.handleOnFocus.bind(this),
          onBlur: this.handleOnBlur.bind(this),
          addTag: this.addTag.bind(this)
        }, this.inputProps()));
```

**Comment by olahol** [comment]
Is this using `defaultRenderInput`? Otherwise you need to filter `addTag`
https://github.com/olahol/react-tagsinput/blob/master/src/index.js#L50

**Comment by angelo-romano** [comment]
yes, I was using `defaultRenderInput`, now it seems working. Thank you!
